# Generated by Django 5.2.3 on 2025-07-03 03:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='用户名不能重复', max_length=255, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, help_text='邮箱不能重复', max_length=255, null=True, unique=True, verbose_name='邮箱')),
                ('phonenumber', models.CharField(help_text='手机号不能为空', max_length=16, unique=True, verbose_name='手机号')),
                ('password', models.CharField(help_text='密码不能为空', max_length=255, verbose_name='密码')),
                ('user_type', models.CharField(choices=[('admin', '管理员'), ('user', '普通用户'), ('guest', '访客')], default='user', max_length=10, verbose_name='用户类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户账号',
                'verbose_name_plural': '用户账号',
                'ordering': ['created_at'],
                'unique_together': {('username', 'email', 'phonenumber')},
            },
        ),
    ]
