# Generated by Django 5.2.4 on 2025-07-10 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userauth", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file",
                    models.FileField(upload_to="user_files/", verbose_name="文件"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="userauth.users",
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户文件",
                "verbose_name_plural": "用户文件",
                "db_table": "user_files",
            },
        ),
    ]
