name: NWT
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.5
  - pip
  - django=5.2
  # mysqlclient=2.2.7  # 已移除MySQL依赖，使用SQLite
  # openssl=3.5.1      # 已移除MySQL依赖，使用SQLite
  - ca-certificates
  - tzdata
  - pip:
      - django-cors-headers==4.7.0
      - djangorestframework==3.16.0
      - djangorestframework-simplejwt==5.5.0
      - pyjwt==2.9.0
      - python-decouple==3.8