name: NWT
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asgiref=3.8.1
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - django=5.2
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libmpdec=4.0.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - lz4-c=1.9.4
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - mysqlclient=2.2.7
  - ncurses=6.4
  - openssl=3.5.1
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.13.5
  - python_abi=3.13
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - sqlparse=0.5.2
  - tk=8.6.14
  - typing_extensions=4.12.2
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - django-cors-headers==4.7.0
      - djangorestframework==3.16.0
      - djangorestframework-simplejwt==5.5.0
      - pyjwt==2.9.0
